models/BoardMembers.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "board_members".
 *
 * @property integer $board_members_id
 * @property integer $school_board_id
 * @property integer $user_id
 * @property integer $is_active
 */
class BoardMembers extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'board_members';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['school_board_id', 'user_id', 'is_active'], 'required'],
            [['school_board_id', 'user_id', 'is_active'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'board_members_id' => 'Board Members ID',
            'school_board_id' => 'School Board ID',
            'user_id' => 'User ID',
            'is_active' => 'Is Active',
        ];
    }
}

controllers/BoardMembersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\BoardMembers;
use app\models\BoardMembersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BoardMembersController implements the CRUD actions for BoardMembers model.
 */
class BoardMembersController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all BoardMembers models.
     * @return mixed
     */
    public function actionIndex($school_board_id)
    {
         $model = new BoardMembers;
         
        $searchModel = new BoardMembersSearch;
        $condition = " school_board_id = {$school_board_id}";
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams(),$condition);
        
        if ($model->load(Yii::$app->request->post())) {
            $model->school_board_id = $school_board_id;
            $model->is_active = 1;
            $model->user_id = Yii::$app->user->id;
          if($model->save(false)){
        return $this->renderAjax('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'model'=> $model,
            'school_board_id'=>$school_board_id,
        ]);
          }
            
        }

        return $this->renderAjax('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'model'=> $model,
            'school_board_id'=>$school_board_id,
        ]);
    }

    /**
     * Displays a single BoardMembers model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(['view', 'id' => $model->board_members_id]);
        } else {
        return $this->render('view', ['model' => $model]);
}
    }

    /**
     * Creates a new BoardMembers model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new BoardMembers;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->board_members_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing BoardMembers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->board_members_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing BoardMembers model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the BoardMembers model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return BoardMembers the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BoardMembers::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/board-members/_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;
use kartik\datecontrol\DateControl;

/**
 * @var yii\web\View $this
 * @var app\models\BoardMembers $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="board-members-form">

    <?php $form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL]); echo Form::widget([

    'model' => $model,
    'form' => $form,
    'columns' => 1,
    'attributes' => [
        
              'user_id' => ['type' => Form::INPUT_WIDGET,
                'widgetClass' => \kartik\select2\Select2::className(),
                'label' => 'Staff',
                'options' => [

                    'data' => yii\helpers\ArrayHelper::map(\app\models\Users::find()->all(), 'user_id', 'firstname'),
                    'options' => [
                        'prompt' => '',
                    //'disabled' => $model->isNewrecord ? false : true,
                    ],
                ],
               
            ],

//'school_board_id'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter School Board ID...']], 

//'user_id'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter User ID...']], 

//'is_active'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Is Active...']], 

    ]


    ]);
    echo Html::submitButton($model->isNewRecord ? Yii::t('app', 'Add') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']);
    ActiveForm::end(); ?>

</div>

views/board-members/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\BoardMembersSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="board-members-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'board_members_id') ?>

    <?= $form->field($model, 'school_board_id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'is_active') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/board-members/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\BoardMembers $model
 */

$this->title = 'Create Board Members';
$this->params['breadcrumbs'][] = ['label' => 'Board Members', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="board-members-create">
    <div class="page-header">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/board-members/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\BoardMembersSearch $searchModel
 */

$this->title = 'Board Members';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="board-members-index">
    <?php Pjax::begin(); echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'board_members_id',
            //'school_board_id',
//            'user_id',
//            'is_active',
              [
                      'label'=>'Member',
                      'attribute'=>'user_id',
                      'value'=>  function ($model){
                          return ucwords(\app\models\Users::findOne($model->user_id)->firstname).'  '.  ucwords(\app\models\Users::findOne($model->user_id)->middlename).' '.  ucwords(\app\models\Users::findOne($model->user_id)->surname).' '.'['.\app\models\StaffPositions::findOne(\app\models\Users::findOne($model->user_id)->staff_position_id)->position_name.']';
                      }
                      
                  ],
                                                              [
            'label' => 'Is Active?',
            'attribute' => 'is_active',
            'vAlign' => 'middle',
            'width' => '10%',
            'value' => function($model) {
                return $model->is_active == 1 ? "<span class='glyphicon glyphicon-ok'></span>" : "<span class='glyphicon glyphicon-remove'></span>";
            },
            'format' => 'raw',
//            'filterType' => GridView::FILTER_SELECT2,
//            'filter' => ['1' => 'Visible', '0' => 'Invisible'],
//            'filterWidgetOptions' => [
//                'pluginOptions' => ['allowClear' => true],
//            ],
//            'filterInputOptions' => ['placeholder' => 'Search...'],
//            'format' => 'raw'
        ],

//            [
//                'class' => 'yii\grid\ActionColumn',
//                'buttons' => [
//                'update' => function ($url, $model) {
//                                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', Yii::$app->urlManager->createUrl(['board-members/view','id' => $model->board_members_id,'edit'=>'t']), [
//                                                    'title' => Yii::t('yii', 'Edit'),
//                                                  ]);}
//
//                ],
//            ],
        ],
        'responsive'=>true,
        'hover'=>true,
        'condensed'=>true,
        'floatHeader'=>false,

        'panel' => [
            'heading'=>' '.  \app\models\SchoolBoard::findOne($school_board_id)->name,
            'type'=>'default',
            //'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> Add', ['create'], ['class' => 'btn btn-success']),                                                                                                                                                          'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset List', ['index'], ['class' => 'btn btn-info']),
            'showFooter'=>false
        ],
    ]); Pjax::end(); ?>
    
    
      <?= $this->render('_form', [
        'model' => $model,
    ]) ?>


</div>

views/board-members/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\BoardMembers $model
 */

$this->title = 'Update Board Members: ' . ' ' . $model->board_members_id;
$this->params['breadcrumbs'][] = ['label' => 'Board Members', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->board_members_id, 'url' => ['view', 'id' => $model->board_members_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="board-members-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/board-members/view.php
<?php

use yii\helpers\Html;
use kartik\detail\DetailView;
use kartik\datecontrol\DateControl;

/**
 * @var yii\web\View $this
 * @var app\models\BoardMembers $model
 */

$this->title = $model->board_members_id;
$this->params['breadcrumbs'][] = ['label' => 'Board Members', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="board-members-view">
    <div class="page-header">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>


    <?= DetailView::widget([
            'model' => $model,
            'condensed'=>false,
            'hover'=>true,
            'mode'=>Yii::$app->request->get('edit')=='t' ? DetailView::MODE_EDIT : DetailView::MODE_VIEW,
            'panel'=>[
            'heading'=>$this->title,
            'type'=>DetailView::TYPE_INFO,
        ],
        'attributes' => [
            'board_members_id',
            'school_board_id',
            'user_id',
            'is_active',
        ],
        'deleteOptions'=>[
        'url'=>['delete', 'id' => $model->board_members_id],
        'data'=>[
        'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?'),
        'method'=>'post',
        ],
        ],
        'enableEditMode'=>true,
    ]) ?>

</div>