controllers/UserManagerController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use app\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use kartik\widgets\FileInput;
use app\models\PasswordForm;
use app\models\Login;
use app\models\LoginForm;
use yii\base\Security;
use yii\filters\AccessControl;
use app\models\LoginsSearch;
use app\models\UserAuditTrailSearch;
use yii\web\ForbiddenHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserManagerController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'delete', 'update', 'profile', 'updatepic', 'updateidentification', 'passwordreset', 'changepassword', 'deactivate', 'students', 'logins-history', 'user-actions'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex($id_to_deactivate = NULL, $id_to_activate = NULL, $subaction = NULL) {

       $searchModel = new UsersSearch;
        $condition = " user_type IN (1,2,3)";
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams(), $condition);


        if ($subaction == 'deactivate') {
            $model_user = Users::findOne($id_to_deactivate);

            $model_user->is_active = 0;
            if ($model_user->save(false)) {
              $objectType = 'UserManager';
            $action = "Deactivated User, user_id =>" . ' ' . $id_to_deactivate;
            \app\models\UserAuditTrail::logAudit($action, $objectType);
                return $this->render('index', [
                            'dataProvider' => $dataProvider,
                            'searchModel' => $searchModel,
                ]);
            }
        }

        if ($subaction == 'activate') {
            $model_user = Users::findOne($id_to_activate);

            $model_user->is_active = 1;
            if ($model_user->save(false)) {
                  $objectType = 'UserManager';
            $action = "Activated User, user_id =>" . ' ' . $id_to_activate;
            \app\models\UserAuditTrail::logAudit($action, $objectType);
                return $this->render('index', [
                            'dataProvider' => $dataProvider,
                            'searchModel' => $searchModel,
                ]);
            }
        }

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
        ]);
    }

    public function actionUpdateidentification($id) {

        $model = $this->findModel($id);
        $oldModel = $model;
        if ($model->load(Yii::$app->request->post())) {
            if ($model->email_address == NULL) {
                $model->addError('email_address', 'Provide Your E-mail Address');
                return $this->render('updateidentification', [
                            'model' => $model,
                ]);
            }
            if ($model->save(false)) {
             $objectType = 'UserManager';
            $action = "Updated his/her Information ";
            \app\models\UserAuditTrail::logAudit($action, $objectType, $oldModel, $model);
                Yii::$app->getSession()->setFlash(
                        'success', 'Identifications Successfuly changed!'
                );
                return $this->redirect(['view', 'id' => $model->user_id]);
            }
        } else {
            return $this->render('updateidentification', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {

        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->user_id]);
            }
        } else {
            return $this->render('view', ['model' => $model]);
        }
    }

    public function actionLoginsHistory($id) {
        $this->layout = 'simple_layout';
        $this->layout = 'simple_layout';
        $condition = "user_id = {$id}";
        $searchModel_logins_History = new \app\models\LoginsSearch();
        $dataProvider_logins_History = $searchModel_logins_History->search(Yii::$app->request->getQueryParams(), $condition);
        return $this->render('view_logins_history', [
                    'dataProvider_logins_History' => $dataProvider_logins_History,
                    'searchModel_logins_History' => $searchModel_logins_History,
        ]);
    }

    public function actionUserActions($id) {
        $this->layout = 'simple_layout';
        $condition = "user_id = {$id}";
        $searchModel_user_audit_trail = new UserAuditTrailSearch;
        $dataProvider_user_audit_trail = $searchModel_user_audit_trail->search(Yii::$app->request->getQueryParams(), $condition);
        return $this->render('view_user_actions', [
                    'dataProvider_user_audit_trail' => $dataProvider_user_audit_trail,
                    'searchModel_user_audit_trail' => $searchModel_user_audit_trail,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {

        $model = new Users;
        if ($model->load(Yii::$app->request->post())) {
            $password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
            $model->password = $password;
            $model->is_default_password = 1;
            $model->is_active = 1;
            if ($model->save(false)) {
              $objectType = 'UserManager';
            $action = "Added User, user_id =>" . ' ' . $model->user_id;
            \app\models\UserAuditTrail::logAudit($action, $objectType);
                return $this->redirect(['view', 'id' => $model->user_id]);
            }
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {

        $model = $this->findModel($id);
        $oldModel = $model;
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                    $objectType = 'UserManager';
            $action = "Updated User Information ";
            \app\models\UserAuditTrail::logAudit($action, $objectType, $oldModel, $model);
                return $this->redirect(['view', 'id' => $model->user_id]);
            }
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    public function actionPasswordreset($id) {

        $model = $this->findModel($id);
        $oldModel = $model;
        if ($model->load(Yii::$app->request->post())) {
            $password = Yii::$app->getSecurity()->generatePasswordHash($model->newpass);
            $model->password = $password;
            $model->is_default_password = 1;
            if ($model->save(false)) {
            $objectType = 'UserManager';
            $action = "Updated User Password";
            \app\models\UserAuditTrail::logAudit($action, $objectType, $oldModel, $model);
                Yii::$app->getSession()->setFlash(
                        'success', 'Password Successfully Changed!'
                );
                return $this->redirect(['view', 'id' => $model->user_id]);
            }
        } else {
            return $this->render('passwordreset', [
                        'model' => $model,
                        'id' => $model->user_id,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();
            $objectType = 'UserManager';
        $action = "Deleted User user_id => " . ' ' . $id;
        \app\models\UserAuditTrail::logAudit($action, $objectType);

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionChangepassword() {

        $model = new PasswordForm;
        $modeluser = Users::find()->where([
                    'user_id' => Yii::$app->user->identity->id
                ])->one();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                try {
                    $hash = Yii::$app->getSecurity()->generatePasswordHash($_POST['PasswordForm']['newpass']);
                    $modeluser->password = $hash;

views/user-manager/_form_update.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;
use kartik\datecontrol\DateControl;
use kartik\builder\TabularForm;

/**
 * @var yii\web\View $this
 * @var app\models\Users $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="users-form">

    <?php
   $form = ActiveForm::begin(['type' => ActiveForm::TYPE_VERTICAL,]);
    echo Form::widget([

        'model' => $model,
        'form' => $form,
        'columns' => 3,
        'attributes' => [

//'student_status_id'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Student Status ID...']], 
 //'is_active'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Is Active...']], 
//'login_counts'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Login Counts...']], 
//'user_type'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter User Type...']], 
            'firstname' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Firstname...', 'maxlength' => 20]],
            'middlename' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Middlename...', 'maxlength' => 20]],
            'sex' => ['type' => Form::INPUT_DROPDOWN_LIST,
                'items' => ['M' => 'Male', 'F' => 'Female'],
                'options' => ['prompt' => '']],
            'salutation' => ['type' => Form::INPUT_DROPDOWN_LIST,
                'items'=> ['Mr.'=>'Mr.','Miss.'=>'Miss.','Ms.'=>'Ms.','Sir.'=>'Sir.','Dr.'=>'Dr.','Prof.'=>'Prof.','Rev.'=>'Rev.','Other'=>'Other'],
                'options' => ['prompt' => '' ]],
            'staff_position_id' => ['type' => Form::INPUT_DROPDOWN_LIST,
                'items' => \yii\helpers\ArrayHelper::map(\app\models\StaffPositions::find()->all(), 'staff_position_id', 'position_name'),
                'options' => ['prompt' => '']],
//'completion_date'=>['type'=> Form::INPUT_WIDGET, 'widgetClass'=>DateControl::classname(),'options'=>['type'=>DateControl::FORMAT_DATE]], 
//'last_login'=>['type'=> Form::INPUT_WIDGET, 'widgetClass'=>DateControl::classname(),'options'=>['type'=>DateControl::FORMAT_DATETIME]], 
            'username' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Username...', 'maxlength' => 200]],
//'registration_number'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Registration Number...', 'maxlength'=>255]], 
            'date_of_birth' => ['type' => Form::INPUT_WIDGET, 'widgetClass' => kartik\date\DatePicker::classname(), 'options' => ['pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd',
                        'todayHighlight' => true]],],
//'admission_date'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Admission Date...', 'maxlength'=>255]], 
//'status_comments'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Status Comments...', 'maxlength'=>255]], 
            'surname' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Surname...', 'maxlength' => 20]],
//'sponsorship_type'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Sponsorship Type...', 'maxlength'=>1]], 
//'place_of_birth'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Place Of Birth...', 'maxlength'=>50]], 
            'mailing_address' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Mailing Address...', 'maxlength' => 150]],
            'telephone_no' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Telephone No...', 'maxlength' => 150]],
            'email_address' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Email Address...', 'maxlength' => 100]],
//'student_id'=>['type'=> TabularForm::INPUT_TEXT, 'options'=>['placeholder'=>'Enter ...']],
            // 'password' => ['type' => Form::INPUT_PASSWORD, 'options' => ['placeholder' => 'Enter Password...', 'maxlength' => 255]],
        ]
    ]);
    echo Html::submitButton($model->isNewRecord ? Yii::t('app', 'Add') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success pull-right' : 'btn btn-primary']);
    ActiveForm::end();
    ?>

</div>

views/user-manager/_passwordreset_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;
use kartik\datecontrol\DateControl;
use kartik\builder\TabularForm;

/**
 * @var yii\web\View $this
 * @var app\models\Users $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="users-form" style="padding-right: 250px; padding-left: 250px;">

    <?php
   $form = ActiveForm::begin(['type' => ActiveForm::TYPE_VERTICAL,]);
    echo Form::widget([

        'model' => $model,
        'form' => $form,
        'columns' => 1,
        'attributes' => [
           'newpass' => ['type' => Form::INPUT_WIDGET,
                'label' => 'New Password',
                'widgetClass' => kartik\password\PasswordInput::classname(), 'options' => ['pluginOptions' => [
                        'showMeter' => false,
                        'toggleMask' => false
                    ]],
                ],
            'repeatnewpass' => ['type' => Form::INPUT_WIDGET,
                'label' => 'Re-Type Password',
                'widgetClass' => kartik\password\PasswordInput::classname(), 'options' => ['pluginOptions' => [
                        'showMeter' => false,
                        'toggleMask' => false
                    ]],],
        ]
    ]);
    echo Html::submitButton($model->isNewRecord ? Yii::t('app', 'Add') : Yii::t('app', 'Reset'), ['class' => $model->isNewRecord ? 'btn btn-success pull-right' : 'btn btn-primary pull-left']);
    ActiveForm::end();
    ?>

</div>

views/user-manager/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;
use kartik\editable\Editable;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\UsersSearch $searchModel
 */
$this->title = 'User Manager';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">


    <?php
    Pjax::begin();
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
//            'user_id',
//            'student_status_id',
//            'registration_number',
            [
                'attribute' => 'username',
                'vAlign' => 'middle',
                'width' => '200px',
                'value' => $model->username,
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => ArrayHelper::map(app\models\Users::find()->orderBy('user_id')->where("user_type = 2")->asArray()->all(), 'username', 'username'),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => ['placeholder' => 'Search...'],
                'format' => 'raw'
            ],
            //'firstname',
            [
                'attribute' => 'firstname',
                'vAlign' => 'middle',
                'width' => '200px',
                'value' => $model->firstname,
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => ArrayHelper::map(app\models\Users::find()->orderBy('user_id')->where("user_type = 2")->asArray()->all(), 'firstname', 'firstname'),
                //'filter'=>ArrayHelper::map(app\models\Users::findBySql("select users.*, concat(ucase(`users`.`surname`),', ',`users`.`firstname`,' ',ifnull(`users`.`middlename`,'')) AS `firstname` from  users")->orderBy('user_id')->asArray()->all(), 'firstname', 'firstname'),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => ['placeholder' => 'Search...'],
                'format' => 'raw'
            ],
            //'surname', 
            [
                'attribute' =>'surname',
                'vAlign' => 'middle',
                'width' => '200px',
                'value' => $model->surname,
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => ArrayHelper::map(app\models\Users::find()->orderBy('user_id')->where("user_type = 2")->asArray()->all(), 'surname', 'surname'),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => ['placeholder' => 'Search...'],
                'format' => 'raw'
            ],

   
//            'middlename',
//            'ps_id',
//            'sex',
//            'date_of_birth',
//            'place_of_birth',
//            'mailing_address',
//            'telephone_no',
            'email_address:email',
//            'admission_date',
//            'sponsorship_type',
//            'status_comments',
//            ['attribute'=>'completion_date','format'=>['date',(isset(Yii::$app->modules['datecontrol']['displaySettings']['date'])) ? Yii::$app->modules['datecontrol']['displaySettings']['date'] : 'd-m-Y']],
            //'username',
//            'password',
            //'is_active', 
              [
                'label' => 'User Type',
                'attribute' =>'user_type',
                'vAlign' => 'middle',
                'width' => '100px',
                'value' => function($model) {
                    return \app\models\Users::getUserType($model->user_type);
                },
                'format' => 'raw',
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => ['2' => 'Garage Owner', '3' => 'Customer'],
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => ['placeholder' => 'Search...'],
                'format' => 'raw'
            ],
            [
                'label' => 'IsActive?',
                'attribute' =>'is_active',
                'vAlign' => 'middle',
                'width' => '30px',
                'value' => function($model) {
                    return $model->is_active == 1 ? "<span class='glyphicon glyphicon-ok'></span>" : "<span class='glyphicon glyphicon-remove'></span>";
                },
                'format' => 'raw',
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => ['1' => 'Active', '0' => 'Inactive'],
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => ['placeholder' => 'Search...'],
                'format' => 'raw'
            ],
//            'login_counts',
//            ['attribute'=>'last_login','format'=>['datetime',(isset(Yii::$app->modules['datecontrol']['displaySettings']['datetime'])) ? Yii::$app->modules['datecontrol']['displaySettings']['datetime'] : 'd-m-Y H:i:s A']],
//            'user_type',
//            'staff_position_id',
//            'salutation',
//            ['attribute'=>'last_password_update_date','format'=>['date',(isset(Yii::$app->modules['datecontrol']['displaySettings']['date'])) ? Yii::$app->modules['datecontrol']['displaySettings']['date'] : 'd-m-Y']],
//            'auth_key',
//            'password_reset_token',
//            ['attribute'=>'created_at','format'=>['date',(isset(Yii::$app->modules['datecontrol']['displaySettings']['date'])) ? Yii::$app->modules['datecontrol']['displaySettings']['date'] : 'd-m-Y']],
//            'created_by',

                  [
                'label' => '',
                'value' => function($model) {
                return Html::a('<span class=" label label-primary"><i class = "glyphicon glyphicon-eye-open"></i>View</span>', Yii::$app->urlManager->createUrl(['user-manager/view', 'id' => $model->user_id, 'view' => 't']), [
                                   'title' => Yii::t('yii', 'View'),
                      ]);
                },
                        'format' => 'raw',
                    ],
                            [
                'label' => '',
                'value' => function($model) {
                
                        $url = Yii::$app->urlManager->createUrl(['user-manager/index', 'id_to_deactivate' => $model->user_id, 'subaction' => 'deactivate']);
                        if ($model->is_active == 1 && $model->user_type != 1) {
                            return Html::a('<span class="label label-danger ">Deactivate</span>', $url, ['title' => Yii::t('yii', 'Deactivate')]);
                        }  else {
                            return ' ';
                        }
                        if ($model->is_active == 0) {
                        $url = Yii::$app->urlManager->createUrl(['user-manager/index', 'id_to_activate' => $model->user_id, 'subaction' => 'activate']);
                        //if ($model->is_active == 0) {
                            return Html::a('<span class="label label-success">Activate</span>', $url, ['title' => Yii::t('yii', 'Activate')]);
                        //} 
                        }
                },
                        'format' => 'raw',
                    ],
//           
                ],
                'responsive' => true,
                'hover' => true,
                'condensed' => true,
                'floatHeader' => false,
                'panel' => [
                    'heading' => ' ',
                    'type' => 'default',
                    'before' => Html::a('<i class="glyphicon glyphicon-plus"></i> Add User', ['create'], ['class' => 'btn btn-primary']), 'after' => Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset List', ['index'], ['class' => 'btn btn-info']),
                    'showFooter' => false
                ],
            ]);
            Pjax::end();
            
           
            ?>

</div>

views/user-manager/view.php
<script>
   function getUserRoutes(){
       var url = <?php echo '"'.\yii\helpers\Url::to(['/auth-assigned-route/index','user_id'=>$model->user_id]).'"'; ?>;
       $('#iframe_user_routes_id').attr('src', url);
   }
</script>

<?php
use yii\helpers\Html;
use kartik\detail\DetailView;
use kartik\datecontrol\DateControl;
use kartik\tabs\TabsX;

/**
 * @var yii\web\View $this
 * @var app\models\Users $model
 */
$this->title = $model->firstname . ' ' . $model->middlename . ' ' . $model->surname;
$this->params['breadcrumbs'][] = ['label' => 'User Manager', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>



<div class="users-view">
    <?php
      ob_start();
        
    if ($model->profile_picture == NULL) {
    $picture = 'default-no-image/default-no-profile-image.png';
} else {
    $picture = $model->profile_picture;
}
?>
    <?php

   echo   DetailView::widget([
        'model' => $model,
        'condensed' => false,
        'hover' => true,
        'mode' => 'view',
        'bordered' =>$bordered,
        'striped' => $striped,
        'condensed' => $condensed,
        'responsive' => $responsive,
         'hideIfEmpty'=>true,
        'hover' => true,
        'hAlign' => $hAlign,
        'vAlign' => $vAlign,
        'fadeDelay' => $fadeDelay,
        //'mode' => Yii::$app->request->get('edit') == 't' ? DetailView::MODE_EDIT : DetailView::MODE_VIEW,
        'panel' => [
            'heading' =>'&nbsp',
            'type' => DetailView::TYPE_DEFAULT,
        ],
        'attributes' => [
               [
                'group' => true,
                  'label' => 'Staff Profile'.' '."<i class='glyphicon glyphicon-user'></i>". Html::a("<i>Update</i>&nbsp<i class='glyphicon glyphicon-pencil'></i>", \yii\helpers\Url::to(['user-manager/updateidentification', 'id' => $model->user_id]), ['class' => 'btn btn success pull-right']) . '<span></li>',
                'rowOptions' => ['class' => 'default']
            ],
                [
                'group' => true,
                'label' => '   <div class="row">
            <div class="col-xs-6 col-md-3">
                <a href="#" class="thumbnail">
                    <img  src="' .$picture. '" width=800 height=900" alt="Profile Photo">
                </a>
            </div>

        </div>',
            ],
//            'user_id',
//            'student_status_id',
//            'registration_number',
            'surname',
            'firstname',
            'middlename',
//            'ps_id',
//            'sex',
            [
                'attribute'=>'sex',
                'value'=>$model->sex == 'M'? 'Male':'Female',
                
            ],
            'date_of_birth',
            'place_of_birth',
            'mailing_address',
            'telephone_no',
            'email_address:email',
//            'admission_date',
//            'sponsorship_type',
//            'status_comments',
       
            'username',
//            'password',
            //'is_active',
            [
                'attribute'=>'is_active',
                'label'=>'Is Active?',
                'value'=>$model->is_active = 1? Active:Inactive,
                
            ],
            
            'login_counts',
            [
                'attribute' => 'last_login',
                'format' => ['datetime', (isset(Yii::$app->modules['datecontrol']['displaySettings']['datetime'])) ? Yii::$app->modules['datecontrol']['displaySettings']['datetime'] : 'd-m-Y H:i:s A'],
                'type' => DetailView::INPUT_WIDGET,
                'widgetOptions' => [
                    'class' => DateControl::classname(),
                    'type' => DateControl::FORMAT_DATETIME
                ]
            ],
//            'user_type',
            [
                'attribute'=>'user_type',
                'label'=>'User Type',
                'value'=>$model->user_type == '2'? 'Garage Owner':'Normal Customer',
                
            ],
         
            'salutation',
      
              [
                'group' => true,
                'label' => 'Reset Password'.' '."<i class='glyphicon glyphicon-lock'></i>". Html::a("<i>Reset</i>&nbsp<i class='glyphicon glyphicon-pencil'></i>", \yii\helpers\Url::to(['user-manager/passwordreset', 'id' => $model->user_id]), ['class' => 'btn btn success pull-right']) . '<span></li>',
                'rowOptions' => ['class' => 'default']
            ],

        ],
        'deleteOptions' => [
            'url' => ['delete', 'id' => $model->user_id],
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ],
        'enableEditMode' => false,
    ]);
   
 $user_details_tab = ob_get_contents(); ob_end_clean();
    ?>
    <?php
     $user_roles_tab = "<iframe src='".\yii\helpers\Url::to(['auth-assignment/index', 'user_id' => $model->user_id])."' width='100%' height='350px'></iframe>";
    ?>
    
    <?php
      $items = [
        [
           'label' => 'User Details',
           'content' => $user_details_tab,
           'id' => 'user_details_tab_id',
        ],
            [
            'label' => 'User Roles',
            'content' => $user_roles_tab,
            'id' => 'user_roles_tab_id',
        ],
        [
          'label' => '<div onclick="getUserRoutes()">Actions Depending on Level</div>',
          'content' => "<iframe src='' width='100%' height='350px' id='iframe_user_routes_id'></iframe>",
          'id' => 'actions_tab_id',
           
        ],
        
        [
            'label' => 'Login History',
            'content' => '  <iframe src='.yii\helpers\Url::to(['/user-manager/logins-history/','id' => $model->user_id]).' width="100%" height="350px" > </iframe>',
            'id' => 'login_history_tab_id',
        ],
        [
            'label' => 'Actions',
            'content' => '<iframe src='.yii\helpers\Url::to(['/user-manager/user-actions/','id' => $model->user_id]).' width="100%" height="350px" ></iframe>',
            'id' => 'action_tab_id',
        ],
               
    ];
    echo TabsX::widget([
    'items' => $items,
    'position' => TabsX::POS_ABOVE,
    'bordered' => true,
    'encodeLabels' => false
   ]);
    ?>
</div>