controllers/PrimaryStudyYearsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Programmes;
use app\models\ProgrammesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\ProgrammeYear;
use app\models\ProgrammeYearSemesters;
use app\models\ProgrammeYearSemesterCourses;
use app\models\InstitutionStructureSearch;
use app\models\StudentSemestersSearch;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;
use app\models\SchoolType;
use app\models\SchoolTypeSearch;

/**
 * StudyYearsController implements the CRUD actions for Programmes model.
 */
class PrimaryStudyYearsController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'delete', 'update', 'configure-study-year', 'results', 'semesters'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Programmes models.
     * @return mixed
     */
    public function actionIndex() {
        $condition = " school_type_id = 1 ";
        $searchModel = new \app\models\SchoolsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams(), $condition);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
        ]);
    }

    public function actionConfigureStudyYear($academic_year_id, $school_id, $activeTab = 'class_year_details_tab', $cy_id = NULL, $study_year = NULL, $cyos_course_id = NULL, $SemActiveTab = NULL, $subaction = NULL, $autoOpen3 = false) {

        if (isset($_POST['hasEditable']) && $cyos_course_id != NULL) {
            $out = '';
            $message = '';
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            end($_POST);
            $key = key($_POST);
            $model = \app\models\ClassYearOfStudyCourses::findOne($cyos_course_id);
            $oldModel = $model;
            $model->$key = $_POST[$key];
            if ($model->validate([$key])) {
                $model->save(false);
                $objectType = 'primary-study-years';
                $action = "Updated primary study years configuration ";
                \app\models\UserAuditTrail::logAudit($action, $objectType, $oldModel, $model);
                switch ($key) {

                    case 'pass_grade_id':
                        $out = \app\models\GradingSystem::findOne($model->$key)->grade;
                        break;

                    case 'contribute_to_final_result':
                        $out = $model->contribute_to_final_result == 1 ? "Yes" : "No";
                        break;

                    case 'is_core':
                        $out = $model->is_core == 1 ? "Core" : "Option";
                        break;
                    default:
                        break;
                }
            } else {
                $message = $model->getErrors($key);
                $out = $message;
            }

            return ['output' => $out, 'message' => $message];
        }


        if ($subaction == 'delete_course') {
            $oldModel = \app\models\ClassYearOfStudyCourses::findOne($cyos_course_id);
            \app\models\ClassYearOfStudyCourses::deleteAll(" cyos_course_id = :cyos_course_id", [":cyos_course_id" => $cyos_course_id]);
            $objectType = 'primary-study-years';
            $action = "Delete class year course, cyos_course_id =>  " . ' ' . $cyos_course_id;
            \app\models\UserAuditTrail::logAudit($action, $objectType, $oldModel, $model);
        }


        $model_cy = new \app\models\ClassYear();
        if ($model_cy->load(Yii::$app->request->post())) {
            $model_cy->academic_year_id = $academic_year_id;
            $model_cy->year_number = $model_cy->study_year;
            $model_cy->school_id = $school_id;


            if (count(\app\models\ClassYear::find()->where(" academic_year_id = :academic_year_id   AND  study_year = :study_year  AND school_id = :school_id  ", [ ':academic_year_id' => $academic_year_id, ':study_year' => $model_cy->study_year, ':school_id' => $school_id])->all()) > 0) {
                $model_cy->addError('study_year', "This class already exist");
                return $this->render('configure-study-year', [
                            'academic_year_id' => $academic_year_id,
                            'model_cy' => $model_cy,
                            'activeTab' => $activeTab,
                            'SemActiveTab' => $SemActiveTab,
                            'school_id' => $school_id,
                ]);
            }
            if ($model_cy->validate(['academic_year_id', 'year_number', 'grading_system_version_id', 'study_year', 'school_id'])) {
                if ($model_cy->save(false)) {
                    $objectType = 'StudyYear';
                    $action = "Added ProgrammeYear , academic_year_id => " . ' ' . $academic_year_id . ' ' . ' ' . 'py_id => ' . ' ' . $model_cy->cy_id;
                    \app\models\UserAuditTrail::logAudit($action, $objectType);

                    return $this->redirect(['configure-study-year', 'academic_year_id' => $academic_year_id, 'activeTab' => 'cy_' . $model_cy->cy_id, 'school_id' => $school_id]);
                }
            } else {
                $activeTab = 'cy_add_year_tab';
            }
        }

        $model_acy = \app\models\AcademicYears::findOne($academic_year_id);

        $model_cyosc = new \app\models\ClassYearOfStudyCourses();

        if ($model_cyosc->load(Yii::$app->request->post())) {
            $model_cyosc->cy_id = $cy_id;
            $model_cyosc->school_id = $school_id;
            if (\app\models\ClassYearOfStudyCourses::find()->where("cy_id IN (SELECT cy_id FROM class_year WHERE cy_id = :cy_id  AND school_id = :school_id  AND study_year = :study_year ) AND course_offering_id = :course_offering_id", [':course_offering_id' => $model_cyosc->course_offering_id, ':cy_id' => $cy_id, ':school_id' => $school_id, ':study_year' => $study_year])->count() > 0) {
                $model_cyosc->addError("course_offering_id", "Course already exists in this class");
                return $this->render('configure-study-year', [
                            'academic_year_id' => $academic_year_id,
                            'model_acy' => $model_acy,
                            'model_cy' => $model_cy,
                            'activeTab' => $activeTab,
                            'SemActiveTab' => $SemActiveTab,
                            'model_cyosc' => $model_cyosc,
                            'school_id' => $school_id,
                ]);
            }

            if ($model_cyosc->validate(['cy_id', 'course_offering_id', 'pass_grade_id', 'contribute_to_final_result', 'is_core'])) {
                if ($model_cyosc->save(false)) {
                    $objectType = 'Primary-study-years';
                    $action = "Added class  Course , academic_year_id => " . ' ' . $academic_year_id . ' ' . "pintake_id =>" . ' ' . ' ' . 'cy_id => ' . ' ' . $cy_id . ' ' . ' ' . ' ' . 'course_offering_id => ' . ' ' . $model_cyosc->course_offering_id;
                    \app\models\UserAuditTrail::logAudit($action, $objectType);
                    return $this->redirect(['configure-study-year', 'academic_year_id' => $academic_year_id, 'school_id' => $school_id, 'activeTab' => 'cy_' . $cy_id]);
                } else {

                    $SemActiveTab = 'cy_add_year_tab';
                }
            }
        }

        return $this->render('configure-study-year', [
                    'academic_year_id' => $academic_year_id,
                    'model_acy' => $model_acy,
                    'model_cy' => $model_cy,
                    'activeTab' => $activeTab,
                    'SemActiveTab' => $SemActiveTab,
                    'model_cyosc' => $model_cyosc,
                    'school_id' => $school_id,
        ]);
    }

    /**
     * Displays a single Programmes model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
//        if (!Yii::$app->user->can('/study-years/view')) {
//            throw new ForbiddenHttpException('You are not allowed to perform this action ! Contact your administrator');
//        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->programme_id]);
        } else {
            return $this->render('view', ['model' => $model]);
        }
    }

    /**
     * Creates a new Programmes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
//        if (!Yii::$app->user->can('/study-years/create')) {
//            throw new ForbiddenHttpException('You are not allowed to perform this action ! Contact your administrator');
//        }
        $model = new Programmes;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $objectType = 'Programmes';
            $action = "Added Programme" . ' ' . 'programme_id =>' . ' ' . $model->programme_id;
            \app\models\UserAuditTrail::logAudit($action, $objectType);
            return $this->redirect(['view', 'id' => $model->programme_id]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**

views/primary-study-years/_academic_years.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;

?>
<div class="academic-years-index">


    <?php  echo GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            

          [
              'attribute'=>'academic_year',
              'value'=>function($model) use ($ps_id){
                return Html::a($model->academic_year, yii\helpers\Url::to(['study-years/configure-study-year','academic_year_id'=>$model->academic_year_id, 'ps_id'=>$ps_id]));
              },
              'format'=>'raw',
          ]
            


        ],

    ]); ?>

</div>

views/primary-study-years/_class_year_courses.php
<?php

use app\models\ProgrammeYearSemesterCoursesSearch;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Json;
use kartik\editable\Editable;
use yii\jui\Dialog;
use app\models\ClassYearOfStudyCoursesSearch;
?>

<?php
$smodel = new ClassYearOfStudyCoursesSearch;
$condition = " cy_id = {$cy_id} AND school_id = {$school_id} ";
$gridColumns = [

    [
        'label' => 'Course',
        'attribute' => 'course_offering_id',
        'value' => function($model) {
            $course_id = app\models\CourseOffering::findOne($model->course_offering_id)->course_id;
            return \app\models\Courses::findOne($course_id)->course_code . ' - ' . \app\models\Courses::findOne($course_id)->course_title;
        }
    ],
    [
        'attribute' => 'pass_grade_id',
        'value' => function($model) use( $model_cy, $model_cyosc, $school_id, $academic_year_id, $model_acy ) {
            return Editable::widget([
                        'name' => 'pass_grade_id',
                        'attribute' => 'pass_grade_id',
                        'value' => \app\models\GradingSystem::findOne($model->pass_grade_id)->grade,
                        'asPopover' => true,
                        'placement' => kartik\popover\PopoverX::ALIGN_LEFT,
                        'header' => 'Pass Grade',
                        //'format' => Editable::FORMAT_BUTTON,
                        'inputType' => Editable::INPUT_DROPDOWN_LIST,
                        'data' => \yii\helpers\ArrayHelper::map(\app\models\GradingSystem::find()->where("grading_system_version_id = {$model_cy->grading_system_version_id} ")->all(), 'grading_system_id', 'grade'),
                        'options' => ['class' => 'form-control', 'prompt' => ''],
                        'editableValueOptions' => ['class' => 'text-success'],
                        'formOptions' => [
                            'action' => \yii\helpers\Url::to(['primary-study-years/configure-study-year',
                                'academic_year_id' => $model_cy->academic_year_id,
                                'activeTab' => 'cy_' . $model_cy->cy_id,
                                'SemActiveTab' => 'sem_tab_' . $model_cy->cy_id,
                                'cy_id' => $model_cy->cy_id,
                                'cyos_course_id' => $model->cyos_course_id,
                                'model_cyosc' => $model_cyosc,
                                'school_id' => $school_id,
                                'academic_year_id' => $academic_year_id,
                                'model_acy' => $model_acy,
                            ]),
                        ]
            ]);
        },
                'format' => 'raw',
            ],
            [
                'attribute' => 'is_core',
                'value' => function($model) use( $model_cy, $model_cyosc, $school_id, $academic_year_id, $model_acy) {

                    return Editable::widget([
                                'name' => 'is_core',
                                'attribute' => 'is_core',
                                'value' => $model->is_core == 1 ? "Core" : "Option",
                                'asPopover' => true,
                                'placement' => kartik\popover\PopoverX::ALIGN_LEFT,
                                'header' => 'Core/Option',
                                //'format' => Editable::FORMAT_BUTTON,
                                'inputType' => Editable::INPUT_DROPDOWN_LIST,
                                'data' => [1 => 'Core', 0 => 'Option'],
                                'options' => ['class' => 'form-control', 'prompt' => ''],
                                'editableValueOptions' => ['class' => 'text-success'],
                                'formOptions' => [
                                    'action' => \yii\helpers\Url::to(['primary-study-years/configure-study-year',
                                        'academic_year_id' => $model_cy->academic_year_id,
                                        'activeTab' => 'cy_' . $model_cy->cy_id,
                                        'SemActiveTab' => 'sem_tab_' . $model_cy->cy_id,
                                        'cy_id' => $model_cy->cy_id,
                                        'model_cyosc' => $model_cyosc,
                                        'cyos_course_id' => $model->cyos_course_id,
                                        'model_cyosc' => $model_cyosc,
                                        'school_id' => $school_id,
                                        'academic_year_id' => $academic_year_id,
                                        'model_acy' => $model_acy,
                                    ]),
                                ]
                    ]);
                },
                        'format' => 'raw',
                    ],
                    [
                        'attribute' => 'contribute_to_final_result',
                        'value' => function($model) use($model_cy, $model_cyosc, $school_id, $academic_year_id, $model_acy) {

                            return Editable::widget([
                                        'name' => 'contribute_to_final_result',
                                        'attribute' => 'contribute_to_final_result',
                                        'value' => $model->contribute_to_final_result == 1 ? "Yes" : "No",
                                        'asPopover' => true,
                                        'placement' => kartik\popover\PopoverX::ALIGN_LEFT,
                                        'header' => 'contributes to final result?',
                                        //'format' => Editable::FORMAT_BUTTON,
                                        'inputType' => Editable::INPUT_DROPDOWN_LIST,
                                        'data' => [1 => 'Yes', 0 => 'No'],
                                        'options' => ['class' => 'form-control', 'prompt' => ''],
                                        'editableValueOptions' => ['class' => 'text-success'],
                                        'formOptions' => [
                                            'action' => \yii\helpers\Url::to(['primary-study-years/configure-study-year',
                                                'academic_year_id' => $model_cy->academic_year_id,
                                                'activeTab' => 'cy_' . $model_cy->cy_id,
                                                'SemActiveTab' => 'sem_tab_' . $model_cy->cy_id,
                                                'cy_id' => $model_cy->cy_id,
                                                'model_cyosc' => $model_cyosc,
                                                'cyos_course_id' => $model->cyos_course_id,
                                                'model_cyosc' => $model_cyosc,
                                                'school_id' => $school_id,
                                                'academic_year_id' => $academic_year_id,
                                                'model_acy' => $model_acy,
                                            ]),
                                        ]
                            ]);
                        },
                                'format' => 'raw',
                            ],
                            [
                                'class' => 'yii\grid\ActionColumn',
                                'template' => '{delete}',
                                'urlCreator' => function($action, $model) use ( $model_cy, $model_cyosc, $school_id, $academic_year_id, $model_acy) {
                                    if ($action == 'delete') {
                                        return \yii\helpers\Url::to(['primary-study-years/configure-study-year',
                                                    'academic_year_id' => $model_cy->academic_year_id,
                                                    'activeTab' => 'cy_' . $model_cy->cy_id,
                                                    'SemActiveTab' => 'sem_tab_' . $model_cy->cy_id,
                                                    'cy_id' => $model_cy->cy_id,
                                                    'model_cyosc' => $model_cyosc,
                                                    'subaction' => 'delete_course',
                                                    'cyos_course_id' => $model->cyos_course_id,
                                                    'model_cyosc' => $model_cyosc,
                                                    'school_id' => $school_id,
                                                    'academic_year_id' => $academic_year_id,
                                                    'model_acy' => $model_acy,
                                        ]);
                                    }
                                }
                                    ],
                                ];

                                echo \kartik\grid\GridView::widget([
                                    'dataProvider' => $smodel->search($params, $condition),
                                    'filterModel' => $searchModel,
                                    'columns' => $gridColumns,
                                    'pjax' => true,
                                    'pjaxSettings' => [
                                        'neverTimeout' => true,
                                    ],
                                    'id' => 'class_year_courses_' . $model_cy->cy_id,
                                ]);

                                echo $this->render('_class_year_courses_form', [
                                    'model' => $model_cyosc,
                                    'model_cy' => $model_cy,
                                    'school_id' => $school_id,
                                    'model_cy' => $model_cy,
                                    'SemActiveTab' => $SemActiveTab,
                                    'academic_year_id' => $academic_year_id,
                                    'model_acy' => $model_acy,
                                    'activeTab' => $activeTab,
                                     'cy_id'=>$cy_id,
                                     'study_year'=>$study_year,
                                ]);
                                ?>

views/primary-study-years/_class_year_courses_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;
use kartik\datecontrol\DateControl;
?>

<div class="programme-year-semester-courses-form">

    <?php
 $form = ActiveForm::begin([
                'type' => ActiveForm::TYPE_VERTICAL,
                'action' => \yii\helpers\Url::to(['primary-study-years/configure-study-year',
                    'academic_year_id' => $model_cy->academic_year_id,
                    'activeTab' => 'cy_' . $model_cy->cy_id,
                    'SemActiveTab' => 'sem_tab_' . $model_cy->cy_id,
                    'cy_id' => $model_cy->cy_id,
                     'model' => $model_cyosc,
                    'model_cy' => $model_cy,
                    'school_id'=>$school_id,
                   'academic_year_id' => $academic_year_id,
                    'model_acy' => $model_acy,
                     'cy_id'=>$cy_id,
                    'study_year'=>$study_year,
         
                ]),
                'id' =>$cy_id,
    ]);

    echo Form::widget([
        'model' => $model,
        'form' => $form,
        'columns' => 1,
        'attributes' => [
            'course_offering_id' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => kartik\select2\Select2::className(),
                'options' => [
                    'attribute' => 'course_offering_id',
                    'model' => $model,
                     'data' => \yii\helpers\ArrayHelper::map(\app\models\Courses::getCurrentVersionPrimaryCourses($school_id,$cy_id), 'course_offering_id', 'course_and_title'),
                    'options' => [
                        'id' => "select2_" .$model_cy->cy_id,
                    ]
                ]
            ],
        ]
    ]);

    echo Form::widget([

        'model' => $model,
        'form' => $form,
        'columns' =>3,
        'attributes' => [
           'pass_grade_id' => ['type' => Form::INPUT_DROPDOWN_LIST, 'items' => \yii\helpers\ArrayHelper::map(\app\models\GradingSystem::find()->where("grading_system_version_id = {$model_cy->grading_system_version_id} ")->all(), 'grading_system_id', 'grade'), 'options' => ['prompt' => '']],
//            'after_supp_grade_id' => ['type' => Form::INPUT_DROPDOWN_LIST, 'items' => \yii\helpers\ArrayHelper::map(\app\models\GradingSystem::find()->where("grading_system_version_id = {$model_cy->grading_system_version_id} ")->all(), 'grading_system_id', 'grade'), 'options' => ['prompt' => '']],
//            'after_carryover_grade_id' => ['type' => Form::INPUT_DROPDOWN_LIST, 'items' => \yii\helpers\ArrayHelper::map(\app\models\GradingSystem::find()->where("grading_system_version_id = {$model_cy->grading_system_version_id} ")->all(), 'grading_system_id', 'grade'), 'options' => ['prompt' => '']],
//            'allowed_to_supp_grade_id' => ['type' => Form::INPUT_DROPDOWN_LIST, 'items' => \yii\helpers\ArrayHelper::map(\app\models\GradingSystem::find()->where("grading_system_version_id = {$model_cy->grading_system_version_id} ")->all(), 'grading_system_id', 'grade'), 'options' => ['prompt' => '']],
//            'allowed_to_repeat_grade_id' => ['type' => Form::INPUT_DROPDOWN_LIST, 'items' => \yii\helpers\ArrayHelper::map(\app\models\GradingSystem::find()->where("grading_system_version_id = {$model_cy->grading_system_version_id} ")->all(), 'grading_system_id', 'grade'), 'options' => ['prompt' => '']],
//            'units' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Units...']],
            'is_core' => ['type' => Form::INPUT_DROPDOWN_LIST, 'items' => ['1' => 'Core', '0' => 'Optional'], 'options' => ['prompt' => '']],
//            //'py_semester_id' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Py Semester ID...']],
//            'CA_Weight' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Ca  Weight...']],
//            'UE_Weight' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Ue  Weight...']],
//            'minimum_CA' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Ue  Weight...']],
//            'minimum_UE' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Ue  Weight...']],
//            'contributes_to_year_gpa' => ['type' => Form::INPUT_CHECKBOX],
            'contribute_to_final_result' => ['type' => Form::INPUT_CHECKBOX],
        ]
    ]);
    echo Html::submitButton('Add', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']);
    ActiveForm::end();
    ?>

</div>

views/primary-study-years/_class_year_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;
use kartik\datecontrol\DateControl;

/**
 * @var yii\web\View $this
 * @var app\models\ProgrammeYear $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="programme-year-form">

    <?php
    $school_type_id = app\models\Schools::findOne($school_id)->school_type_id;
    $form = ActiveForm::begin(['type' => ActiveForm::TYPE_VERTICAL]);
    echo Form::widget([

        'model' => $model,
        'form' => $form,
        'columns' => 3,
        'attributes' => [

            //'pintake_id' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Ps ID...']],
            //'academic_year_id' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Academic Year ID...']],
            'study_year' => ['type' => Form::INPUT_DROPDOWN_LIST, 
                'items'=> \yii\helpers\ArrayHelper::map(app\models\ClassDescription::find()->all(),'class_number','description'),  
                'options' => ['prompt' => '']],
            //'gpa_to_sit_supp' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Gpa To Sit Supp...']],
            //'max_failed_courses' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Max Failed Courses...']],
           // 'min_gpa_to_carry' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Min Gpa To Carry...']],
            'required_year_units' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => 'Enter Required Year Units...']],
            'grading_system_version_id' => ['type' => Form::INPUT_DROPDOWN_LIST, 'items'=>  \yii\helpers\ArrayHelper::map(\app\models\GradingSystemVersions::find()->where(" school_type_id = {$school_type_id}")->all(), 'grading_system_version_id', 'description'), 'options' => ['prompt' => '']],
            //'year_contributes_to_gpa' => ['type' => Form::INPUT_CHECKBOX],
        ]
    ]);
    echo Html::submitButton('Add', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']);
    ActiveForm::end();
    ?>

</div>

views/primary-study-years/configure-study-year.php
<?php

use kartik\tabs\TabsX;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\jui\Dialog;

$this->title = 'Configure Primary Classes -  ' . ' ' . 'Academic Year:' . ' ' . $model_acy->academic_year . '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp';
$this->params['breadcrumbs'][] = ['label' => 'Primary Schools', 'url' => ['primary-study-years/index']];
$this->params['breadcrumbs'][] = 'Configure Programme Study Years - ' . $model_acy->academic_year;
?>

<h4><span class="label label-success">School Name </span>:<span class="label label-info"><?= app\models\Schools::findOne($school_id)->school_name. ' '. \app\models\SchoolType::findOne(app\models\Schools::findOne($school_id)->school_type_id)->school_type?></span> &nbsp;&nbsp; 
</h4><br>

<?php
$class_years = app\models\ClassYear::find()->where("academic_year_id = :academic_year_id  AND school_id = :school_id ", [':academic_year_id' => $model_acy->academic_year_id, ':school_id'=>$school_id])->orderBy("study_year ASC")->all();
$items = [];


foreach ($class_years as $key => $value) {

    $arrayItem = [
        'label' => \app\models\ClassDescription::find()->where("class_number = {$value->study_year}")->one()->description,
        'content' => $this->render('_class_years', [
            'model_cyosc' => $model_cyosc,
            'school_id'=>$school_id,
            'model_cy' => $value,
            'SemActiveTab' => $SemActiveTab,
             'academic_year_id' => $academic_year_id,
                'model_acy' => $model_acy,
                'activeTab' => $activeTab,
                ]),
        'id' => 'cy_' . $value->cy_id,
        'active' => ($activeTab == 'cy_' . $value->cy_id)
    ];
    array_push($items, $arrayItem);
}

$arrayItem = [
    'label' => '<i class="glyphicon glyphicon-plus"></i> Add Year',
    'content' => $this->render('_class_year_form', ['model' => $model_cy, 'school_id'=>$school_id]),
    'id' => 'cy_add_year_tab',
    'active' => ($activeTab == 'cy_add_year_tab')
];
array_push($items, $arrayItem);

echo TabsX::widget([
    'items' => $items,
    'position' => TabsX::POS_ABOVE,
    'bordered' => true,
    'encodeLabels' => false
]);

\yii\jui\Dialog::begin([
    'clientOptions' => [
        'title' => 'Adding new Class Year',
        'autoOpen' => false,
        'width' => '900',
        'height' => '500',
    ],
    'options' => [
        'id' => 'new_programme_year_dialog_id',
    ],
]);
?>

<!--<iframe src="<?php echo Url::to(['programme-year/create', 'academic_year_id' => $model_acy->academic_year_id]); ?>" width="100%" height="100%" class="myiframe"> </iframe>-->

<?php
\yii\jui\Dialog::end();
//echo Html::a('<i class="glyphicon glyphicon-plus"></i> Add New Programme Year', "#", ['class' => 'btn btn-success', 'onclick' => "$('#new_programme_year_dialog_id').dialog('open'); return false; ", 'style'=>'margin-top: 10px']);
//echo $this->render('_form_add_study_year', ['model' => $model_cy]);
?>